services:
  slserver:
    image: node:20
    container_name: slserver
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - TESTNET_ORACLE_SEED=${TESTNET_ORACLE_SEED}
      - MAINNET_ORACLE_SEED=${MAINNET_ORACLE_SEED}
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - "127.0.0.1:3002:3002"
