import { Router, Request, Response } from "express";
import { getFullnodeUrl, IotaClient, IotaTransactionBlockResponse } from "@iota/iota-sdk/client";
import { Ed25519Keypair } from "@iota/iota-sdk/keypairs/ed25519";
import { getObject } from "./utils/getObject";
import { ObjectEdge, searchObjectsByType } from "./utils/searchObjectByType";
import { Transaction, TransactionArgument } from "@iota/iota-sdk/transactions";
import { gasStationCfg, singAndExecTx } from "./utils/signAndExecTx";
// Import Move bindings generated by your Move-to-JS tool


const router = Router();

//--- Inizializzazione delle costanti e variabili globali ---
let creditToken: string;
let policy: string;
let controllerCap: string;
let OIDcontrollerCap: string;
let defaultPackageID: string;
let client: IotaClient;
let seed: string;
let keyPair: Ed25519Keypair;
let network: string;
let configuration_object: string;
let graphqlProvider: string;
let gasStation: gasStationCfg = {
  gasStation1URL: "https://gas1.objectid.io",
  gasStation1Token: "1111",
  gasStation2URL: "https://gas2.objectid.io",
  gasStation2Token: "1111",
};
let useGasStation = false;
let tokenCreditType: string;
let policyTokenType: string;

/**
 * Inizializza il client IOTA, le costanti Move e le variabili d'ambiente.
 */
async function init() {
  seed = process.env.SEED || "88f389b6a8806a3207778b31d73b6aacca06d6cadcf84d5a6c533ae53d250852";
  network = process.env.NETWORK || "testnet";
  configuration_object =
    process.env.CONFIGURATION_OBJECT || "0x8b8a88963245733f4109b3277ee4691790d178c1be5261f9272e63c1cf184f88";
  graphqlProvider = process.env.GRAPHQL_PROVIDER || "https://graphql.testnet.iota.cafe/";

  creditToken = "0x19ff793c834e52ba313e5bffe8bd5231ae6593bfdf6143fc4c65a5e140d3a539";
  controllerCap = "0xfd0c97bb8e7053cf893248cd95d56458d1e12dd1842b53ca8baa96e4a9617d17";
  OIDcontrollerCap = "0x5fc756968a4577949fe24839b750b397b08f6e323d7da6f3e2ed706a8c2798f2";

  client = new IotaClient({ url: getFullnodeUrl(network) });
  keyPair = Ed25519Keypair.deriveKeypairFromSeed(seed);

  const onchainCfgObject = (await getObject(client, configuration_object)) as any;

  if (!onchainCfgObject || !onchainCfgObject.content || !onchainCfgObject.content.fields) {
    throw new Error("Invalid configuration object received from the blockchain");
  }

  defaultPackageID = onchainCfgObject.content.fields.official_packages[0];

  tokenCreditType = `0x2::token::Token<${defaultPackageID}::oid_credit::OID_CREDIT>`;
  policyTokenType = `0x2::token::TokenPolicy<${defaultPackageID}::oid_credit::OID_CREDIT>`;

  const pedges: ObjectEdge[] = await searchObjectsByType(policyTokenType, graphqlProvider);

  policy = pedges[0].node.address;

  console.log("defaultPackageID", defaultPackageID);
  console.log("credit token", creditToken);
  console.log("OIDcontrollerCap", OIDcontrollerCap);
  console.log("Private key:", keyPair.getSecretKey());
  console.log("address:", keyPair.toIotaAddress());
}

init();

/**
 * Wrapper per invocare una funzione Move sullo smart contract.
 * @param modulePath Path completo alla funzione Move
 * @param args Argomenti da passare
 */
async function sendMoveTx(
  target: string, // `${defaultPackageID}::update_geo_location`;
  args: TransactionArgument[]
) {
  try {
    // Prepara la tx con i binding Move
    const tx = new Transaction();
    tx.moveCall({
      arguments: args,
      target,
    });

    await singAndExecTx(
      network,
      client,
      gasStation,
      useGasStation,
      keyPair,
      tx,
      {
        onSuccess: (result: IotaTransactionBlockResponse) => {
          return { success: true, txId: result, error: "" };
        },
        onError: (err: unknown) => {
          return { success: false, txId: undefined, error: "" };
        },
      }
    );
  } catch (err: any) {
    return { success: false, txId: undefined, error: err.message };
  }
}

/**
 * Crea un nuovo oggetto OID
 */
router.post("/create_object", async (req: Request, res: Response) => {
  try {
    const { object_type, product_url, description, op_code, immutable_metadata, mutable_metadata, geo_location } =
      req.body;

    const tx = new Transaction();

    const moveFunction = "objectId::oid_object::create_object";

    const txArguments = [
      tx.object(creditToken),
      tx.object(policy),
      tx.object(OIDcontrollerCap),
      tx.pure.string(object_type),
      tx.pure.string(product_url),
      tx.pure.string(description),
      tx.pure.string(op_code),
      tx.pure.string(JSON.stringify(immutable_metadata)),
      tx.pure.string(JSON.stringify(mutable_metadata)),
      tx.pure.string(geo_location),
      tx.object("0x6"),
    ];
    
    const sender = keyPair.toIotaAddress();
    tx.setGasBudget(10000000);
    tx.setSender(sender);

    const response = await sendMoveTx(moveFunction, txArguments);

    if (response && response.success) {
      res.json({ success: true, txId: response.txId });
    } else {
      res.json({ success: false, txId: undefined });
    }
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

router.post("/update_object_metadata", async (req: Request, res: Response) => {
  try {
    const { objectUid, new_mutable_metadata } = req.body;
    const txId = await sendMoveTx("objectId::oid_object::update_object_mutable_metadata", [
      creditToken,
      policy,
      controllerCap,
      objectUid,
      new_mutable_metadata,
    ]);
    res.json({ success: true, txId });
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});


router.stack.forEach((r: any) => {
  if (r.route && r.route.path) {
    console.log(`✅ Route attiva: ${r.route.path}`);
  } else if (r.name === 'router') {
    console.log('➡️ Sub-router o middleware attivo');
  } else {
    console.log('❓ Entry non riconosciuta nello stack:', r);
  }
});

export default router;
