import { Router, Request, Response } from "express";
import { ExecutionStatus, getFullnodeUrl, IotaClient, IotaTransactionBlockResponse } from "@iota/iota-sdk/client";
import { Ed25519Keypair } from "@iota/iota-sdk/keypairs/ed25519";
import { getObject } from "./utils/getObject";
import { ObjectEdge, searchObjectsByType } from "./utils/searchObjectByType";
import { Arguments, Transaction, TransactionArgument } from "@iota/iota-sdk/transactions";
import type { gasStationCfg } from "./utils/signAndExecTx";
import { singAndExecTx } from "./utils/signAndExecTx";
// Import Move bindings generated by your Move-to-JS tool

const router = Router();

const nullSeed = "0000000000000000000000000000000000000000000000000000000000000000";

let policy: string;
let packageID: string;
let client: IotaClient;
let keyPair: Ed25519Keypair;
let graphqlProvider: string;
let gasStation: gasStationCfg;
let useGasStation = true;
let tokenCreditType: string;
let policyTokenType: string;
let OIDobjectType: string;

function logInputs(route: string, inputs: any) {
  console.log("==============================================================");
  console.log(` ${route}`);
  console.log("==============================================================");
  for (const [key, value] of Object.entries(inputs)) {
    if (key.toLowerCase() === "seed") continue;
    console.log(`${key}:`, value);
  }
}

/**
 * client IOTA
 */

async function setupEnv(seed: string, network: string) {
  client = new IotaClient({ url: getFullnodeUrl(network) });
  keyPair = Ed25519Keypair.deriveKeypairFromSeed(seed);
  if (network == "testnet") {
    packageID = "0x79857c1738f31d70165149678ae051d5bffbaa26dbb66a25ad835e09f2180ae5";
    graphqlProvider = process.env.GRAPHQL_PROVIDER || "https://graphql.testnet.iota.cafe/";
    gasStation = {
      gasStation1URL: "https://gas1.objectid.io",
      gasStation1Token: "1111",
      gasStation2URL: "https://gas2.objectid.io",
      gasStation2Token: "1111",
    };
  } // mainnet
  else {
    packageID = "0xc6b77b8ab151fda5c98b544bda1f769e259146dc4388324e6737ecb9ab1a7465";
    graphqlProvider = process.env.GRAPHQL_PROVIDER || "https://graphql.mainnet.iota.cafe/";
    gasStation = {
      gasStation1URL: "https://m-gas1.objectid.io",
      gasStation1Token: "1111",
      gasStation2URL: "https://m-gas2.objectid.io",
      gasStation2Token: "1111",
    };
  }

  tokenCreditType = `0x2::token::Token<${packageID}::oid_credit::OID_CREDIT>`;
  policyTokenType = `0x2::token::TokenPolicy<${packageID}::oid_credit::OID_CREDIT>`;
  OIDobjectType = `${packageID}::oid_object::OIDObject`;

  const pedges: ObjectEdge[] = await searchObjectsByType(policyTokenType, null, graphqlProvider);
  policy = pedges[0].node.address;

  return { client, keyPair, graphqlProvider, policy };
}

router.post("/create_object", async (req: Request, res: Response) => {
  try {
    const {
      seed,
      network,
      creditToken,
      OIDcontrollerCap,
      object_type,
      product_url,
      product_img_url,
      description,
      op_code,
      immutable_metadata,
      mutable_metadata,
      geo_location,
    } = req.body;

    logInputs("create_object", {
      network,
      creditToken,
      OIDcontrollerCap,
      object_type,
      product_url,
      product_img_url,
      description,
      op_code,
      immutable_metadata,
      mutable_metadata,
      geo_location,
    });

    const { client, keyPair, graphqlProvider, policy } = await setupEnv(seed, network);

    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::create_object";

    logInputs("create_object", {
      network,
      creditToken,
      policy,
      OIDcontrollerCap,
      object_type,
      product_url,
      op_code,
      immutable_metadata,
      mutable_metadata,
      geo_location,
    });

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(OIDcontrollerCap),
        tx.pure.string(object_type),
        tx.pure.string(product_url),
        tx.pure.string(product_img_url),
        tx.pure.string(description),
        tx.pure.string(op_code),
        tx.pure.string(JSON.stringify(immutable_metadata)),
        tx.pure.string(JSON.stringify(mutable_metadata)),
        tx.pure.string(geo_location),
        tx.object("0x6"),
      ],
      target: moveFunction,
    });

    const sender = keyPair.toIotaAddress();
    tx.setGasBudget(10000000);
    tx.setSender(sender);

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result: IotaTransactionBlockResponse) => {
        const status = result.effects?.status as ExecutionStatus;
        const txDigest = result.digest;

        if (status.status == "success") {
          const newObjectId = result.effects?.created?.[0]?.reference?.objectId;

          res.json({ success: true, txDigest, newObjectId });
          console.log("Success, txDigest: ", txDigest, newObjectId);
        } else {
          res.json({ success: false, txDigest, error: status.error });
          console.error("Object creation failed.");
        }
      },
      onError: (err: any) => {
        res.json({ success: false, undefined, error: undefined });
        console.error("Object creation failed:", err);
      },
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/update_object_mutable_metadata", async (req: Request, res: Response) => {
  try {
    const { seed, network, creditToken, controllerCap, object, new_mutable_metadata } = req.body;

    logInputs("update_object_mutable_metadata", {
      network,
      creditToken,
      controllerCap,
      object,
      new_mutable_metadata,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);

    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::update_object_mutable_metadata";

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(controllerCap),
        tx.object(object),
        tx.pure.string(new_mutable_metadata),
      ],
      target: moveFunction,
    });

    const sender = keyPair.toIotaAddress();
    tx.setGasBudget(10000000);
    tx.setSender(sender);

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result: IotaTransactionBlockResponse) => {
        const status = result.effects?.status as ExecutionStatus;
        const txDigest = result.digest;

        if (status.status == "success") {
          res.json({ success: true, txDigest });
          console.log("Success, txDigest: ", txDigest);
        } else {
          res.json({ success: false, txDigest, error: status.error });
          console.error("Object creation failed.");
        }
      },
      onError: (err: any) => {
        res.json({ success: false, undefined, error: undefined });
        console.error("Object creation failed:", err);
      },
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/update_owner_did", async (req: Request, res: Response) => {
  try {
    const { seed, network, creditToken, controllerCap, object, new_owner_did } = req.body;

    logInputs("update_owner_did", {
      network,
      creditToken,
      controllerCap,
      object,
      new_owner_did,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);

    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::update_owner_did";

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(controllerCap),
        tx.object(object),
        tx.pure.string(new_owner_did),
      ],
      target: moveFunction,
    });

    tx.setGasBudget(10_000_000);
    tx.setSender(keyPair.toIotaAddress());

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result) => res.json({ success: true, txDigest: result.digest }),
      onError: (err) => res.json({ success: false, error: err }),
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/update_agent_did", async (req: Request, res: Response) => {
  try {
    const { seed, network, creditToken, controllerCap, object, new_agent_did } = req.body;
    logInputs("update_agent_did", {
      network,
      creditToken,
      controllerCap,
      object,
      new_agent_did,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);

    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::update_agent_did";

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(controllerCap),
        tx.object(object),
        tx.pure.string(new_agent_did),
      ],
      target: moveFunction,
    });

    tx.setGasBudget(10_000_000);
    tx.setSender(keyPair.toIotaAddress());

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result) => res.json({ success: true, txDigest: result.digest }),
      onError: (err) => res.json({ success: false, error: err }),
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/update_geo_location", async (req: Request, res: Response) => {
  try {
    const { seed, network, creditToken, controllerCap, object, new_location } = req.body;
    logInputs("update_geo_location", {
      network,
      creditToken,
      controllerCap,
      object,
      new_location,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);

    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::update_geo_location";

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(controllerCap),
        tx.object(object),
        tx.pure.string(new_location),
      ],
      target: moveFunction,
    });

    tx.setGasBudget(10_000_000);
    tx.setSender(keyPair.toIotaAddress());

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result) => res.json({ success: true, txDigest: result.digest }),
      onError: (err) => res.json({ success: false, error: err }),
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/delete_object", async (req: Request, res: Response) => {
  try {
    const { seed, network, creditToken, controllerCap, object } = req.body;
    logInputs("delete_object", {
      network,
      creditToken,
      controllerCap,
      object,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);

    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::delete_object";

    tx.moveCall({
      arguments: [tx.object(creditToken), tx.object(policy), tx.object(controllerCap), tx.object(object)],
      target: moveFunction,
    });

    tx.setGasBudget(10_000_000);
    tx.setSender(keyPair.toIotaAddress());

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result) => res.json({ success: true, txDigest: result.digest }),
      onError: (err) => res.json({ success: false, error: err }),
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/create_event", async (req: Request, res: Response) => {
  try {
    const { seed, network, creditToken, controllerCap, object, event_type, immutable_metadata, mutable_metadata } =
      req.body;

    logInputs("create_event", {
      network,
      creditToken,
      controllerCap,
      object,
      event_type,
      immutable_metadata,
      mutable_metadata,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);
    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::create_event";

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(controllerCap),
        tx.pure.address(object),
        tx.pure.string(event_type),
        tx.pure.string(immutable_metadata),
        tx.pure.string(mutable_metadata),
      ],
      target: moveFunction,
    });

    tx.setGasBudget(10_000_000);
    tx.setSender(keyPair.toIotaAddress());

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result) => res.json({ success: true, txDigest: result.digest }),
      onError: (err) => res.json({ success: false, error: err }),
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/update_event_mutable_metadata", async (req: Request, res: Response) => {
  try {
    const { seed, network, creditToken, controllerCap, event, new_mutable_metadata } = req.body;
    logInputs("update_event_mutable_metadata", {
      network,
      creditToken,
      controllerCap,
      event,
      new_mutable_metadata,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);
    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::update_event_mutable_metadata";

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(controllerCap),
        tx.object(event),
        tx.pure.string(new_mutable_metadata),
      ],
      target: moveFunction,
    });

    tx.setGasBudget(10_000_000);
    tx.setSender(keyPair.toIotaAddress());

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result) => res.json({ success: true, txDigest: result.digest }),
      onError: (err) => res.json({ success: false, error: err }),
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/delete_event", async (req: Request, res: Response) => {
  try {
    const { seed, network, creditToken, controllerCap, object, event } = req.body;
    logInputs("delete_event", {
      network,
      creditToken,
      controllerCap,
      object,
      event,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);
    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::delete_event";

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(controllerCap),
        tx.object(object),
        tx.object(event),
      ],
      target: moveFunction,
    });

    tx.setGasBudget(10_000_000);
    tx.setSender(keyPair.toIotaAddress());

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result) => res.json({ success: true, txDigest: result.digest }),
      onError: (err) => res.json({ success: false, error: err }),
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/create_counter", async (req: Request, res: Response) => {
  try {
    const {
      seed,
      network,
      creditToken,
      controllerCap,
      object,
      value,
      unit,
      step,
      immutable_metadata,
      mutable_metadata,
    } = req.body;

    logInputs("create_counter", {
      network,
      creditToken,
      controllerCap,
      object,
      value,
      unit,
      step,
      immutable_metadata,
      mutable_metadata,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);
    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::create_counter";

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(controllerCap),
        tx.pure.address(object),
        tx.pure.u64(value),
        tx.pure.string(unit),
        tx.pure.u64(step),
        tx.pure.string(immutable_metadata),
        tx.pure.string(mutable_metadata),
      ],
      target: moveFunction,
    });

    tx.setGasBudget(10_000_000);
    tx.setSender(keyPair.toIotaAddress());

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result) => res.json({ success: true, txDigest: result.digest }),
      onError: (err) => res.json({ success: false, error: err }),
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/delete_counter", async (req: Request, res: Response) => {
  try {
    const { seed, network, creditToken, controllerCap, object, counter } = req.body;

    logInputs("delete_counter", {
      network,
      creditToken,
      controllerCap,
      object,
      counter,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);
    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::delete_counter";

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(controllerCap),
        tx.object(object),
        tx.object(counter),
      ],
      target: moveFunction,
    });

    tx.setGasBudget(10_000_000);
    tx.setSender(keyPair.toIotaAddress());

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result) => res.json({ success: true, txDigest: result.digest }),
      onError: (err) => res.json({ success: false, error: err }),
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/counter_stepup", async (req: Request, res: Response) => {
  try {
    const { seed, network, creditToken, controllerCap, object, counter } = req.body;

    logInputs("counter_stepup", {
      network,
      creditToken,
      controllerCap,
      object,
      counter,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);
    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::counter_stepup";

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(controllerCap),
        tx.object(object),
        tx.object(counter),
      ],
      target: moveFunction,
    });

    tx.setGasBudget(10_000_000);
    tx.setSender(keyPair.toIotaAddress());

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result) => res.json({ success: true, txDigest: result.digest }),
      onError: (err) => res.json({ success: false, error: err }),
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/counter_stepdown", async (req: Request, res: Response) => {
  try {
    const { seed, network, creditToken, controllerCap, objectId, counter } = req.body;
    logInputs("counter_stepdown", {
      network,
      creditToken,
      controllerCap,
      objectId,
      counter,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);
    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::counter_stepdown";

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(controllerCap),
        tx.object(objectId),
        tx.object(counter),
      ],
      target: moveFunction,
    });

    tx.setGasBudget(10_000_000);
    tx.setSender(keyPair.toIotaAddress());

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result) => res.json({ success: true, txDigest: result.digest }),
      onError: (err) => res.json({ success: false, error: err }),
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/counter_set_value", async (req: Request, res: Response) => {
  try {
    const { seed, network, creditToken, controllerCap, objectId, counter, new_value } = req.body;
    logInputs("counter_set_value", {
      network,
      creditToken,
      controllerCap,
      objectId,
      counter,
      new_value,
    });

    const { client, keyPair, policy } = await setupEnv(seed, network);
    const tx = new Transaction();
    const moveFunction = packageID + "::oid_object::counter_set_value";

    tx.moveCall({
      arguments: [
        tx.object(creditToken),
        tx.object(policy),
        tx.object(controllerCap),
        tx.object(objectId),
        tx.object(counter),
        tx.pure.u64(new_value),
      ],
      target: moveFunction,
    });

    tx.setGasBudget(10_000_000);
    tx.setSender(keyPair.toIotaAddress());

    singAndExecTx(network, client, gasStation, useGasStation, keyPair, tx, {
      onSuccess: (result) => res.json({ success: true, txDigest: result.digest }),
      onError: (err) => res.json({ success: false, error: err }),
      onSettled: () => {},
    });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/get_object", async (req: Request, res: Response) => {
  try {
    const { network, objectId } = req.body;

    logInputs("counter_set_value", {
      network,
      objectId,
    });

    const { client } = await setupEnv(nullSeed, network);

    const objectData = getObject(client, network);

    res.json({ success: true, objectData });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.post("/get_objects", async (req: Request, res: Response) => {
  try {
    const { network, after } = req.body;

    logInputs("get_objects", {
      network,
      after,
    });

    const { graphqlProvider } = await setupEnv(nullSeed, network);

    const objectsList = await searchObjectsByType(OIDobjectType, after, graphqlProvider);

    console.log("objectType:", OIDobjectType);

    console.log("objectsList:", objectsList);

    res.json({ success: true, objectsList });
  } catch (err) {
    console.error("Unexpected error:", err);
  }
});

router.stack.forEach((r: any) => {
  if (r.route && r.route.path) {
    console.log(`✅ Route active: ${r.route.path}`);
  } else if (r.name === "router") {
    console.log("➡️ Sub-router o middleware active");
  } else {
    console.log("❓ Unknown entry in the stack:", r);
  }
});

export default router;
